## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: EventDrivenMicroServiceArchitecture
  properties:
    services:
      - name: NotificationWorker
        properties:
          description: NotificationWorker description.
          osType: Windows
          codePackages:
            - name: NotificationWorker
              image: notificationworker:dev
              resources:
                requests:
                  cpu: "[parameters('NotificationWorker_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: EventDrivenMicroServiceArchitectureNetwork
