## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: EventDrivenMicroServiceArchitecture
  properties:
    services:
      - name: FriendsApi
        properties:
          description: FriendsApi description.
          osType: Windows
          codePackages:
            - name: FriendsApi
              image: friendsapi:dev
              endpoints:
                - name: FriendsApiListener
                  port: 80
#              environmentVariables:
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: "[parameters('FriendsApi_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: EventDrivenMicroServiceArchitectureNetwork
              endpointRefs:
                - name: FriendsApiListener
